### ISSUE TITLE
Help Me Pls

### ISSUE THREAD

**Issue by GeekPowerFelixSun** [guanghaofan/wafermap#1]
小哥，你这个有中文版的么，我很感兴趣，有中文教程么？

**Comment by guanghaofan** [comment]
@GeekPowerFelix 
Sorry, There's no document in Chinese Version! Please follow the instructions to  install this plugin into your Kibana.
不好意思，没有中文版本的文档， 请按照说明安装这个插件，即可使用，不需要教程！
